"""empty message

Revision ID: 028d848d38bc
Revises: d1c7062b7990
Create Date: 2019-10-07 22:29:42.430369

"""

# revision identifiers, used by Alembic.
revision = '028d848d38bc'
down_revision = 'd1c7062b7990'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('board_id', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('employee_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('simulations', sa.Column('project', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'simulations', 'boards', ['board_id'], ['id'])
    op.create_foreign_key(None, 'simulations', 'projects', ['project'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.drop_column('simulations', 'project')
    op.drop_column('simulations', 'employee_ids')
    op.drop_column('simulations', 'board_id')
    # ### end Alembic commands ###
