"""empty message

Revision ID: 31bc366c09f4
Revises: 028d848d38bc
Create Date: 2019-10-08 11:46:45.472027

"""

# revision identifiers, used by Alembic.
revision = '31bc366c09f4'
down_revision = '028d848d38bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('until', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'until')
    # ### end Alembic commands ###
