"""empty message

Revision ID: 8e31420ae930
Revises: c2653631e36e
Create Date: 2019-10-04 17:49:13.172589

"""

# revision identifiers, used by Alembic.
revision = '8e31420ae930'
down_revision = 'c2653631e36e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('order', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'columns', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'columns', type_='unique')
    op.drop_column('columns', 'order')
    # ### end Alembic commands ###
