"""empty message

Revision ID: d1c7062b7990
Revises: 8e31420ae930
Create Date: 2019-10-04 20:00:45.517781

"""

# revision identifiers, used by Alembic.
revision = 'd1c7062b7990'
down_revision = '8e31420ae930'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'content')
    # ### end Alembic commands ###
